FROM node:14.7.0-alpine

# set /app as work directory
WORKDIR /app

# copy package.json to work directory, so that we install npm dependencies
COPY package.json /app

# install npm dependencies
RUN npm install # OR `RUN yarn install`
RUN npm install -g firebase-tools@10.4.0
RUN npm install -g nodemon